index:
    path: /index
    controller: Eventum\Controller\IndexController::defaultAction

confirm:
    path: /confirm
    methods: GET
    controller: Eventum\Controller\ConfirmController::defaultAction

setup:
    path: /setup
    methods: GET|POST
    controller: Eventum\Controller\Setup\SetupController::defaultAction

front:
    path: /
    controller: Eventum\Controller\FrontController::indexAction

# vim:ts=4:sw=4:et
